### ISSUE TITLE
添加knife4j插件,使用文档相关注解部分接口不显示

### ISSUE THREAD

**Issue by 525bigword** [noear/solon#174]
文档配置类
```
package cn.poem.solon.core.config;


import cn.poem.solon.core.utils.ApiResult;
import com.github.xiaoymin.knife4j.solon.extension.OpenApiExtensionResolver;
import io.swagger.models.Contact;
import io.swagger.models.Scheme;
import org.noear.solon.annotation.Bean;
import org.noear.solon.annotation.Configuration;
import org.noear.solon.annotation.Inject;
import org.noear.solon.docs.DocDocket;
import org.noear.solon.docs.models.ApiInfo;

/***
 * 接口文档配置类
 */
@Configuration
public class DocConfig {
    // knife4j 的配置，由它承载
    @Inject
    OpenApiExtensionResolver openApiExtensionResolver;

    /**
     * 简单点的
     */
    @Bean("appApi")
    public DocDocket appApi() {
        //根据情况增加 "knife4j.setting" （可选）
        return new DocDocket()
                .basicAuth(openApiExtensionResolver.getSetting().getBasic())
                .vendorExtensions(openApiExtensionResolver.buildExtensions())
                .groupName("app端接口")
                .schemes("Scheme.HTTP")
                .globalResult(ApiResult.class)
                .globalResponseInData(true)
                .apis("com.swagger.demo.controller.app")
                .securityDefinitionInHeader("token");

    }

    /**
     * 丰富点的
     */
    @Bean("adminApi")
    public DocDocket adminApi() {
        return new DocDocket()
                .groupName("admin端接口")
                .info(new ApiInfo().title("在线文档")
                        .description("在线API文档")
                        .termsOfService("https://gitee.com/noear/solon")
                        .contact(new Contact().name("demo")
                                .url("https://gitee.com/noear/solon")
                                .email("837713748@qq.com"))
                        .version("1.0"))
                .schemes(Scheme.HTTP.toValue(), Scheme.HTTPS.toValue())
                .globalResponseInData(true)
                .globalResult(ApiResult.class)
                .apis("cn.poem.solon.admin.system.controller") //可以加多条，以包名为单位
                ;//.securityDefinitionInHeader("token");

    }
}

```

app.yml
```
knife4j:
  enable: true
  basic:
    enable: true
    username: admin
    password: 123456
  setting:
    enableOpenApi: false
    enableSwaggerModels: false
    enableFooter: false
```

接口类
```
package cn.poem.solon.admin.system.controller;

import cn.poem.solon.admin.system.domain.dto.PoemMenuFromDTO;
import cn.poem.solon.admin.system.enums.OpenType;
import cn.poem.solon.core.extension.BaseController;
import cn.poem.solon.core.utils.ApiResult;
import cn.poem.solon.core.validat.Insert;
import cn.poem.solon.core.validat.Update;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import cn.poem.solon.admin.system.domain.vo.PoemMenuTreeVO;
import cn.poem.solon.admin.system.domain.entity.PoemMenu;
import cn.poem.solon.admin.system.service.IPoemMenuService;
import org.noear.solon.annotation.*;
import org.noear.solon.validation.annotation.Valid;
import org.noear.solon.validation.annotation.Validated;

import java.util.ArrayList;
import java.util.List;

/***
 * 菜单Controller
 */
@Controller
@Valid
@Mapping("poemMenu")
@Api("菜单管理")
public class PoemMenuController extends BaseController<IPoemMenuService> {

    @Inject
    IPoemMenuService baseService;

//    @ApiOperation("列表查询")
    @Get
    @Mapping("list")
    public ApiResult<List<PoemMenuTreeVO>> list(){
        List<PoemMenuTreeVO> result=new ArrayList<>();
        //表单管理
        List<PoemMenuTreeVO> children1 = new ArrayList();
        children1.add(new PoemMenuTreeVO().setLabel("主控台").setKey("console").setType(1).setOpenType(1).setSubtitle("console").setAuth("console").setPath("/dashboard/console"));
        children1.add(new PoemMenuTreeVO().setLabel("工作台").setKey("workplace").setType(1).setOpenType(1).setSubtitle("workplace").setAuth("workplace").setPath("/dashboard/workplace"));
        result.add(new PoemMenuTreeVO().setLabel("Dashboard").setSubtitle("dashboard").setKey("dashboard").setAuth("dashboard").setPath("/dashboard").setType(1).setOpenType(1).setChildren(children1));


        //dashboard
        List<PoemMenuTreeVO> children2 = new ArrayList();
        children2.add(new PoemMenuTreeVO().setLabel("基础表单").setKey("basic-form").setType(1).setOpenType(1).setSubtitle("basic-form").setAuth("basic-form").setPath("/form/basic-form"));
        children2.add(new PoemMenuTreeVO().setLabel("分步表单").setKey("step-form").setType(1).setOpenType(1).setSubtitle("step-form").setAuth("step-form").setPath("/form/step-form"));
        result.add(new PoemMenuTreeVO().setLabel("表单管理").setSubtitle("form").setKey("form").setAuth("form").setPath("/form").setType(1).setOpenType(1).setChildren(children2));

        return ApiResult.ok(result);
    }

    @ApiOperation("菜单详情")
    @Get
    @Mapping("{menuId}")
    public ApiResult<PoemMenu> info(Long menuId){
        return ApiResult.ok(baseService.getById(menuId));
    }

    @ApiOperation("新增菜单")
    @Post
    @Mapping
    public ApiResult<?> add(@Body @Validated(Insert.class) PoemMenuFromDTO poemMenuFromDTO){
        PoemMenu poemMenu = poemMenuFromDTO.toEntity();
//        PoemMenu save = baseService.save(poemMenu);
//        if(save.getMenuId()!=null){
//            return ApiResult.ok();
//        }
        return ApiResult.ok(poemMenu);
    }

    @ApiOperation("修改菜单")
    @Put
    @Mapping
    public ApiResult<?> edit(@Body @Validated(Update.class) PoemMenuFromDTO poemMenuFromDTO){
        PoemMenu poemMenu = poemMenuFromDTO.toEntity();
        boolean result = baseService.updateById(poemMenu);
        return toResult(result);
    }

    @ApiOperation("删除菜单")
    @Delete
    @Mapping("/{menuId}")
    public ApiResult<?> remove(Long menuId){
        boolean result = baseService.deleteById(menuId);
        return toResult(result);
    }

}

```

最终显示
![image](https://github.com/noear/solon/assets/50405154/7747fb17-eb50-4032-99bd-79238dd1dbf3)

后续操作:
后续我将修改接口的Mapping添加了路径后,能正确显示修改接口的文档
在我将列表接口的@ApiOperation("列表查询")放开注释后，启动项目，访问文档出现栈内存溢出,疑似因为该接口的响应类型特殊

```
@Data
@Accessors(chain = true)
@ApiModel("菜单树")
public class PoemMenuTreeVO {
    private String label;
    private String key;
    @ApiModelProperty("菜单id")
    private Long menuId;
    @ApiModelProperty("菜单类型 1:侧边菜单 2:按钮")
    private Integer type;
    @ApiModelProperty("副标题")
    private String subtitle;
    @ApiModelProperty("打开方式 1:当前窗口  2:新窗口")
    private Integer openType;
    @ApiModelProperty("权限字符")
    private String auth;
    @ApiModelProperty("路径")
    private String path;
    @ApiModelProperty("下级菜单")
    private List<PoemMenuTreeVO> children;
}
```

栈内存溢出日志
```
java.lang.StackOverflowError
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeArgument(SignatureParser.java:399)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeArguments(SignatureParser.java:380)
	at java.base/sun.reflect.generics.parser.SignatureParser.parsePackageNameAndSimpleClassTypeSignature(SignatureParser.java:335)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:304)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:277)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:469)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
	at java.base/sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:53)
	at java.base/sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:42)
	at java.base/sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
	at java.base/sun.reflect.generics.repository.FieldRepository.<init>(FieldRepository.java:49)
	at java.base/sun.reflect.generics.repository.FieldRepository.make(FieldRepository.java:66)
	at java.base/java.lang.reflect.Field.getGenericInfo(Field.java:109)
	at java.base/java.lang.reflect.Field.getGenericType(Field.java:276)
	at org.noear.solon.docs.openapi2.Swagger2Builder.parseSwaggerModel(Swagger2Builder.java:592)
```

问题汇总:
1.knife4j部分接口不显示
2.疑似递归类型的数据结构会栈溢出

**Comment by noear** [comment]
谢谢反馈！

**Comment by noear** [comment]
修好了！

**Comment by noear** [comment]
2.4.0-RC ，可以拉取了。试下
