### ISSUE TITLE
[Solon 1.7.2] Problem with list transfer

### ISSUE THREAD

**Issue by danielsawan** [noear/solon#38]
Hello,

I developed a simple case where i have an interface like this on both client and server with a server side implementation
```
@NamiClient(path = "/helloService")
public interface HelloService {
	public String hello(String name);
	public String helloList(List<User> users);
}
```
with a server side implementation

```
@Mapping(value = "/helloService", method = MethodType.SOCKET)
@Remoting
public class HelloServiceImpl implements HelloService {

	public String hello(String name) {
		return "hello " + name;
	}

	public String helloList(List<User> users) {
		return "" + users.size();
	}
}
```

My server code

```
// socket
ConsumerEx<SolonApp> config = new ConsumerEx<SolonApp>() {
	@Override
	public void accept(SolonApp app) throws Throwable {
		app.enableHttp(false);
		app.enableSocketD(true);
	}
};

Solon.start(Server.class, args, config);
```

My client code that work
```
Solon.start(Client.class, args, app -> app.enableHttp(false));
HelloService helloService = SocketD.create("tcp://192.168.1.21:28080/helloService", HelloService.class); // localhost
System.out.println(helloService.hello("test"));
```

My client code that doesn't work
```
Solon.start(Client.class, args, app -> app.enableHttp(false));
HelloService helloService = SocketD.create("tcp://192.168.1.21:28080/helloService", HelloService.class); // localhost

User user1 = new User();
user1.setNom("rgrg");
user1.setPrenom("rgrg");

List<User> userList = new ArrayList<User>();
userList.add(user1);
userList.add(user1);

System.out.println(helloService.helloList(userList));
```

The error i got from client
```
[0mException in thread "main" java.lang.RuntimeException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String that contains type id (for subtype of java.util.List)
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1799)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1533)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._locateTypeId(AsArrayTypeDeserializer.java:164)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:96)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2823)
	at org.noear.solon.serialization.jackson.JacksonActionExecutor.changeValue(JacksonActionExecutor.java:66)
	at org.noear.solon.core.handle.ActionExecutorDefault.buildArgs(ActionExecutorDefault.java:96)
	at org.noear.solon.core.handle.ActionExecutorDefault.execute(ActionExecutorDefault.java:42)
	at org.noear.solon.core.handle.Action.callDo(Action.java:312)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:254)
	at org.noear.solon.core.handle.Action.invoke(Action.java:184)
	at org.noear.solon.core.handle.Action.handle(Action.java:163)
	at org.noear.solon.core.route.RouterHandler.handleOne(RouterHandler.java:81)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:46)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:688)
	at org.noear.solon.core.handle.FilterChainNode.doFilter(FilterChainNode.java:22)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:657)
	at org.noear.solon.socketd.SocketContextHandler.handle(SocketContextHandler.java:31)
	at org.noear.solon.socketd.RouterListener.onMessage0(RouterListener.java:114)
	at org.noear.solon.socketd.RouterListener.lambda$onMessage$1(RouterListener.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

The error i got from server
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String that contains type id (for subtype of java.util.List)
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1799)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1533)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._locateTypeId(AsArrayTypeDeserializer.java:164)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:96)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2823)
	at org.noear.solon.serialization.jackson.JacksonActionExecutor.changeValue(JacksonActionExecutor.java:66)
	at org.noear.solon.core.handle.ActionExecutorDefault.buildArgs(ActionExecutorDefault.java:96)
	at org.noear.solon.core.handle.ActionExecutorDefault.execute(ActionExecutorDefault.java:42)
	at org.noear.solon.core.handle.Action.callDo(Action.java:312)
	at org.noear.solon.core.handle.Action.invoke0(Action.java:254)
	at org.noear.solon.core.handle.Action.invoke(Action.java:184)
	at org.noear.solon.core.handle.Action.handle(Action.java:163)
	at org.noear.solon.core.route.RouterHandler.handleOne(RouterHandler.java:81)
	at org.noear.solon.core.route.RouterHandler.handle(RouterHandler.java:46)
	at org.noear.solon.SolonApp.doFilter(SolonApp.java:688)
	at org.noear.solon.core.handle.FilterChainNode.doFilter(FilterChainNode.java:22)
	at org.noear.solon.SolonApp.tryHandle(SolonApp.java:657)
	at org.noear.solon.socketd.SocketContextHandler.handle(SocketContextHandler.java:31)
	at org.noear.solon.socketd.RouterListener.onMessage0(RouterListener.java:114)
	at org.noear.solon.socketd.RouterListener.lambda$onMessage$1(RouterListener.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
My server pom dependencies
```
<!-- for server -->
<dependency>
    <groupId>org.noear</groupId>
    <artifactId>solon.boot.socketd.smartsocket</artifactId>
    <version>1.7.2</version>
</dependency>
    
<dependency>
      <groupId>org.noear</groupId>
      <artifactId>nami.channel.socketd.smartsocket</artifactId>
      <version>1.7.2</version>
</dependency>

<dependency>
    <groupId>org.noear</groupId>
    <artifactId>solon.serialization.jackson</artifactId>
    <version>1.7.2</version>
</dependency>
```

My client pom dependencies
```
<!-- for client -->
<dependency>
      <groupId>org.noear</groupId>
      <artifactId>solon.socketd.client.smartsocket</artifactId>
      <version>1.7.2</version>
</dependency>

<dependency>
      <groupId>org.noear</groupId>
      <artifactId>nami.coder.jackson</artifactId>
      <version>1.7.2</version>
</dependency>
```

Do you have an idea about why i can't pass list as parameter to server ?

Thanks for your help !

**Comment by danielsawan** [comment]
With SnackSerializer it seems to work but i have a problem when both method in interface have the same name. Then i get a ClassCastException because i guess he is calling the first method with a list instead of calling the second method.

example
```
@Mapping(value = "/helloService", method = MethodType.SOCKET)
@Remoting
public class HelloServiceImpl implements HelloService {

	public String hello(String name) {
		return "hello " + name;
	}

	public String hello(List<User> users) {
		return "" + users.size();
	}
}
```

**Comment by noear** [comment]
因为资料不全，给你带来不便，非常抱歉。

**Comment by noear** [comment]
我马上补写一篇官网文章。

**Comment by noear** [comment]
需要把：
solon.serialization.jackson
nami.coder.jackson

换成：
solon.serialization.snack3
nami.coder.snack3

//jackson 目前适配得还不是很好

**Comment by noear** [comment]
或者换成：
solon.serialization.fastjson
nami.coder.fastjson

//目前 jackson 的编码适配，只适用于非泛型的 //我个人对它不是很熟，所以适配差了点儿

**Comment by noear** [comment]
**支持序列化方案**

| 通道 | 说明 | 
| -------- | -------- | 
| Form     | 表单模式     | 
| Json     | 适配有：snack3、fastjson  （推荐）  | 
| Hessian 通道     | 适配有：hessian  （推荐）  | 
| Protostuff 通道     | 适配有：protostuff     |

**Comment by noear** [comment]
关于 SockteD rpc 的官网文章，做了优化：

http://solon.noear.org/article/67

**Comment by noear** [comment]
```java
//使用Nami构建，指定编码器
HelloService rpc = Nami.builder().url("tcp://localhost:28080/demoe/rpc")
                                   .encoder(SnackTypeEncoder.instance)
                                   .create(HelloService.class);
```

具体看下官网的优化过的文章：http://solon.noear.org/article/67

**Comment by danielsawan** [comment]
杰克逊允许通过以下代码将jsonArray绑定到列表中

```
ObjectMapper mapper = new ObjectMapper()
List<Person> personList = mapper.readValue(jsonString, new TypeReference<List<Person>>() {});
```
如果我理解，我不应该使用jackson，而应该使用Snack3，对吗？但是我需要在我的项目中忽略一些字段。在Snack3中是否有与@JsonIgnore相当的东西？

谢谢你的帮助 !

**Comment by noear** [comment]
Snack3 有两种方式可以控制相同效果：
1. @ONodeAttr 注解
2. transient  关键字

**Comment by noear** [comment]
```
List<Person> personList = mapper.readValue(jsonString, new TypeReference<List<Person>>() {});

//这种特性snack3也支持的
List<Person> personList = ONode.deserialize(jsonString, (new ArrayList<Person>(){}).getClass());
//或者
List<Person> personList = ONode.deserialize(jsonString, new TypeRef<List<Person>>(){}.getType());
```

**Comment by danielsawan** [comment]
Thank you very much !
