### ISSUE TITLE
异常：动态代理重复签名 java.lang.ClassFormatError: Duplicate method name&signature in class file

### ISSUE THREAD

**Issue by zengyufei** [noear/solon#59]
简单描述：建立抽象类并写一个抽象方法，@Service继承并实现，启动就会报错。

版本：solon 1.9.3
JDK版本：1.8

复现步骤：

1-抽象类
```
public abstract class TestBase {
	public abstract void sayHello();
}
```

2-继承类
```
@Service
public class TestBaseService extends TestBase {
    @Override
    public void sayHello() {
    }
}
```

4-报错信息
```

java.lang.ClassFormatError: Duplicate method name&signature in class file com/zyf/controller/caches/$Proxy_TestBaseService
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.noear.solon.aspect.asm.AsmProxyClassLoader.transfer2Class(AsmProxyClassLoader.java:20)
	at org.noear.solon.aspect.asm.AsmProxy.newProxyInstance(AsmProxy.java:119)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:40)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:26)
	at org.noear.solon.aspect.BeanProxy.getProxy(BeanProxy.java:29)
	at org.noear.solon.core.BeanWrap.proxySet(BeanWrap.java:94)
	at org.noear.solon.aspect.AspectUtil.binding(AspectUtil.java:32)
	at org.noear.solon.aspect.integration.XPluginImp.lambda$startOld$4(XPluginImp.java:46)
	at org.noear.solon.core.AopContext.lambda$tryCreateBean$10(AopContext.java:397)
	at org.noear.solon.core.AopContext.tryCreateBean0(AopContext.java:426)
	at org.noear.solon.core.AopContext.tryCreateBean(AopContext.java:394)
	at org.noear.solon.core.AopContext.lambda$beanScan$9(AopContext.java:353)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:348)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:319)
	at org.noear.solon.SolonApp.run(SolonApp.java:130)
	at org.noear.solon.Solon.start(Solon.java:140)
	at org.noear.solon.Solon.start(Solon.java:90)
	at org.noear.solon.Solon.start(Solon.java:77)
	at com.zyf.App.main(App.java:10)
```

**Comment by noear** [comment]
有可能是 asm 版本冲突了。。。solon.aspect 用的是 9.2 版本

**Comment by noear** [comment]
感觉反馈。。。我试了你那个 demo ：

确实出错了。原因，可能跟你的服务类（TestBaseService）的基类（TestBase）是虚似类有关。你先改成接口用，就好了。

//具体，我再研究下是什么原因

**Comment by noear** [comment]
1.9.4-M1 版本，已解决这个问题。。。麻烦试一下

**Comment by zengyufei** [comment]
1.9.4-M1 版本, 确认解决，测试通过

**Comment by noear** [comment]
1.9.4 已发布：）

**Comment by russleung44** [comment]
## 同样问题
版本: solon 1.10.3 
jdk: 18

报错信息
```java
java.lang.ClassFormatError: Duplicate method name "update" with signature "(Lcom.tony.log4m.base.BaseEntity;)Ljava.lang.Object;" in class file com/tony/log4m/service/impl/$Proxy_TagServiceImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:875)
	at org.noear.solon.aspect.asm.AsmProxyClassLoader.transfer2Class(AsmProxyClassLoader.java:14)
	at org.noear.solon.aspect.asm.AsmProxy.newProxyInstance(AsmProxy.java:126)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:40)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:26)
	at org.noear.solon.aspect.BeanProxy.getProxy(BeanProxy.java:33)
	at org.noear.solon.core.BeanWrap.proxySet(BeanWrap.java:113)
	at org.noear.solon.aspect.AspectUtil.binding(AspectUtil.java:32)
	at org.noear.solon.aspect.integration.XPluginImp.lambda$start$1(XPluginImp.java:23)
	at org.noear.solon.core.AopContext.lambda$tryCreateBean$10(AopContext.java:398)
	at org.noear.solon.core.AopContext.tryCreateBean0(AopContext.java:427)
	at org.noear.solon.core.AopContext.tryCreateBean(AopContext.java:395)
	at org.noear.solon.core.AopContext.lambda$beanScan$9(AopContext.java:354)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:349)
	at org.noear.solon.core.AopContext.beanScan(AopContext.java:320)
	at org.noear.solon.SolonApp.run(SolonApp.java:128)
	at org.noear.solon.Solon.start(Solon.java:149)
	at org.noear.solon.Solon.start(Solon.java:99)
	at com.tony.log4m.Log4MApplication.main(Log4MApplication.java:7)

```

### 相关类信息

```java
@Service
public class TagServiceImpl extends CrudServiceImpl<TagDao, Tag, TagDTO, TagConvert> implements TagService {

    @Override
    public TagDTO update(Tag tag) {
        return super.update(tag);
    }

}
```


```java
public abstract class CrudServiceImpl<M extends BaseMapper<T>, T extends BaseEntity, E, C extends BasicConvert> implements CrudService<T, E> {

    public static DbContext db() {
        return DbConfig.master;
    }

    @Inject
    private C convert;

    @Inject
    private M dao;


    @Override
    public E update(E e) {
        if (e == null) {
            return null;
        }

        T t = toSource(e);
        return update(t);
    }
}
```

```java
public interface CrudService<T extends BaseEntity, E> {

    E update(T t);

    E update(E e);

}
```

**Comment by noear** [comment]
> 

麻烦试一下 jdk11 是否正常？

**Comment by russleung44** [comment]
也报

![image](https://user-images.githubusercontent.com/56534185/193190415-4e30ff90-37fd-40c1-9a80-6b88973f37b2.png)

**Comment by noear** [comment]
好的，我实验一下

**Comment by noear** [comment]
我根据你上面提供的信息，实验 了一下。。。运行是正常的，麻烦你帮忙看一下，这代码是否有哪里不对：

https://github.com/noear/solon/tree/dev/_solon_extend/solon.aspect/src/test/java/test2

**Comment by russleung44** [comment]
重载多一个 update 

```java
public abstract class CrudServiceImpl<M , T extends BaseEntity, E, C extends BasicConvert> implements CrudService<T, E> {

    public static Object db() {
        return null;
    }

    @Inject
    private C convert;

    @Inject
    private M dao;


    @Override
    public E update(E e) {
        if (e == null) {
            return null;
        }

        //T t = toSource(e);
        return update(e);
    }

    @Override
    public E update(T t) {
        if (t == null) {
            return null;
        }

        return null;
    }
}
```

**Comment by noear** [comment]
会尽快处理此问题

**Comment by russleung44** [comment]
OK, 我先注掉一个

**Comment by noear** [comment]
调整好了，现在发布一个：1.10.5-M1 的测试版本。。。发布完成后，我会再通知你。到时，帮忙测试一下

**Comment by russleung44** [comment]
可

**Comment by noear** [comment]
已发布半小时了，不过中央仓库还是没有。。。还得再等。

**Comment by noear** [comment]
1.10.5-M1 ，中央仓库可以拉取了！麻烦试下。

**Comment by russleung44** [comment]
我拉不到, 请问是用哪个仓库的地址 ?

**Comment by noear** [comment]
赞。那你先玩着。。。有问题，随时反馈：）

**Comment by noear** [comment]
建议加到 qq 群里，方便交流

**Comment by russleung44** [comment]
现在基本不使用QQ了，有没有tg的群

**Comment by russleung44** [comment]
Telegram...
