### ISSUE TITLE
jdk17 test 代码执行时抛出异常

### ISSUE THREAD

**Issue by busyfree** [noear/solon#70]
```java
// MyTest.java

import cn.td.App;
import cn.td.mapper.UserMapper;
import cn.td.po.User;
import cn.td.service.UserService;
import com.baomidou.mybatisplus.solon.plugins.pagination.Page;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.noear.solon.annotation.Inject;
import org.noear.solon.test.SolonJUnit4ClassRunner;
import org.noear.solon.test.SolonTest;

@RunWith(SolonJUnit4ClassRunner.class)
@SolonTest(App.class)
public class MyTest {
    @Inject
    UserService service;

    @Inject
    UserMapper mapper;

    @Test
    public void test01() {
//        获取所有的用户
        service.list().forEach(System.out::println);
    }

    @Test
    public void test02() {
//        逻辑删除
        System.out.println(service.removeById(911327233));
    }

    @Test
    public void test03() {
//        分页
        Page<User> page = service.page(new Page<>(1, 2));
        System.out.println(page.getPages());
        System.out.println(page.getTotal());
        System.out.println("====================");
        page.getRecords().forEach(System.out::println);
    }

    @Test
    public void test04() {
        System.out.println(mapper.get());
    }


}

```
```java
java.lang.RuntimeException: java.lang.ClassFormatError: Illegal class name "/$Proxy_MyTest" in class file <Unknown>

	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:44)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:26)
	at org.noear.solon.aspect.BeanProxy.getProxy(BeanProxy.java:33)
	at org.noear.solon.test.SolonJUnit4ClassRunner.createTest(SolonJUnit4ClassRunner.java:113)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ClassFormatError: Illegal class name "/$Proxy_MyTest" in class file <Unknown>
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:874)
	at org.noear.solon.aspect.asm.AsmProxyClassLoader.transfer2Class(AsmProxyClassLoader.java:14)
	at org.noear.solon.aspect.asm.AsmProxy.newProxyInstance(AsmProxy.java:126)
	at org.noear.solon.aspect.BeanInvocationHandler.<init>(BeanInvocationHandler.java:40)
	... 25 more
```

**Comment by noear** [comment]
麻烦把这个类，放到一个包下（比如 demo）试一下

**Comment by busyfree** [comment]
感谢，放在包下面可以运行了。

**Comment by noear** [comment]
通了就好。。。目前：Solon 项目的类，都要放在包下。这也是避免在扫描时，范围过大：）

//可以加到 qq 群里来，交流更及时

**Comment by busyfree** [comment]
群号是这个？22200020

**Comment by noear** [comment]
是的：）
